struct Pawn;

type Piece = Pawn;

struct GameBoard {
    squares: [Option<Piece>; 64]
}

fn main() {
    let board = GameBoard {
        squares: [
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
            Some(Pawn {}),
        ]
    };
}
